services:
  workspace:
    command: sleep infinity
    image: debian:trixie
    volumes:
      - .:/workspaces/bbn2:cached
      - ~/.claude:/home/vscode/.claude
      - ~/.copilot:/home/vscode/.copilot
